### ISSUE TITLE
Luodaan repo Travikseen ja Codecoviin 

### ISSUE THREAD

**Issue by vaahtokarkki** [otahontas/tuho#13]
https://codecov.io/
https://travis-ci.com/

Muut kun repon omistajat ei lisätä noihin. Ei tarvii muuta kun lisätä tää repo noihin palveluihin, voin hoitaa conffauksen

**Comment by otahontas** [comment]
Lisätty. Avaa issue uudestaan/pingaa, jos tarvii lisätä codecovissa tai traviksessa samaan tiimiin.
